local ArsenalWeapons = {
	[1] = {
		[1] = {
			weaponModel = game.ReplicatedStorage.Guns["Assault Rifle"];
			text = "Assault Rifle";
			cost = 75;
			timeToProduce = 3;
		};
		[2] = {
			weaponModel = game.ReplicatedStorage.Guns["SMG"];
			text = "SMG";
			cost = 55;
			timeToProduce = 1;
		};
	};
	[2] = {
		[1] = {
			weaponModel = game.ReplicatedStorage.Guns["Laser Drill"];
			text = "Laser Drill";
			cost = 75;
			timeToProduce = 6;
		};

	};
	[3] = {
		[1] = {
			weaponModel = game.ReplicatedStorage.Guns["Rocket Launcher"];
			text = "Rocket Launcher";
			cost = 75;
			timeToProduce = 3;
		}

	};
	[4] = {

	};
	[5] = {

	};
	[6] = {

	};
}

return ArsenalWeapons